name: listInputDir
namespace: utils
description: List the contents of a directory and parse contained fastq files
arguments:
  - name: "--input"
    alternatives: [-i]
    type: file
    description: Path to the directory containing fastq files
    required: true
    example: fastq_dir
  - name: --pools
    description: "Pool names to include. By default all pools are selected for analysis."
    type: string
    multiple: true
  - name: "--r1_output"
    type: file
    description: Path to read 1 fastq/fasta file
    direction: output
  - name: "--r2_output"
    type: file
    description: Path to read 2 fastq/fasta file
    direction: output
  - name: "--lane"
    type: string
    description: Lane nr
    direction: output
  - name: "--sample"
    type: string
    description: Sample nr
    direction: output
  - name: "--sample_id"
    type: string
    description: Sample name
    direction: output

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf

runners:
  - type: nextflow

engines:
  - type: native
